# API keys for financial data backends
# At least one backend must be configured for the bot to function
alphavantageKey: mYsUp3rs3CretKEY12345
fmpKey: 

# Triggers
stocktrigger: stonks
cryptotrigger: hodl

